name: Latest StackOverflow Activity Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest StackOverflow activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: StackOverflow
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/3824249"
          max_post_count: 5
          commit_message: "Updated with the latest StackOverflow activity"
          committer_username: "branmcconnell"
          committer_email: "brandon@dreamthinkbuild.com"